app:
  key: "Z28tZ3JwYy1ib2lsZXJwbGF0ZQ=="
  name: "Go gRPC Boilerplate"
  nameSlug: "go-grpc-boilerplate"

grpcServer:
  port: 50051
  useReflection: true # enable reflection for grpcui
  maxSendMsgSize: 10 # in MB
  maxRecvMsgSize: 10 # in MB
  useTls: false
  tlsCertFile: "script/ssl/server.crt"
  tlsKeyFile: "script/ssl/server.pem"

log:
  level: "debug"
  stacktraceLevel: "error" # debug, info, warn, error, panic, fatal
  fileEnabled: false
  fileSize: 10 # MB
  filePath: "storage/log/log.log"
  fileCompress: false # enable log file compress before rotate
  maxAge: 1 # days to keep log files
  maxBackups: 10 # umber of log files

postgres:
  host: "localhost" # use "host.docker.internal" if you run app inside docker container
  port: 54322
  database: "my_db"
  schema: "my_schema"
  username: "my_user"
  password: "my_password"
  maxConnections: 20
  maxIdleConnections: 10

Redis:
  - host: "localhost"
    port: 63799
    password: ""
    db: 0

scheduler:
  timezone: "Asia/Bangkok"
# schedules:
#   - cron: "0 */20 * * * *"
#     job: "SyncAll"
