env: "dev" # dev, staging, production

app:
  key: "my-app-key"
  name: "My App"
  nameSlug: "my-app"

grpcServer:
  port: 50051
  reflection: true # enable reflection for grpcui
  useTls: false
  tlsCertFile: "certs/server.crt"
  tlsKeyFile: "certs/server.key"

grpcClient:
  - name: "grpc-endpoint-1"
    host: "localhost"
    port: 50051
    useTls: false
    tlsCertFile: "certs/server.crt" # should be CA cert file

log:
  level: "debug"
  stacktraceLevel: "error" # debug, info, warn, error, dpanic, panic, fatal
  fileEnabled: false
  fileSize: 10 # MB
  filePath: "log/log.log"
  fileCompress: false # enable log file compress before rotate
  maxAge: 1 # days to keep log files
  maxBackups: 10 # umber of log files

postgres:
  host: "localhost" # use "host.docker.internal" if you run app inside docker container
  port: 54322
  database: "my_db"
  schema: "my_schema"
  username: "my_user"
  password: "my_password"
  maxConnections: 20
  maxIdleConnections: 10

Redis:
  - host: "localhost"
    port: 63791
    password: ""
    db: 0

scheduler:
  timezone: "Asia/Bangkok"
# schedules:
#   - cron: "0 */20 * * * *"
#     job: "SyncAll"
